#!/bin/bash

currentDir=$PWD
relativeDir=`realpath --relative-to="$HOME/code" "$currentDir"`
url="http://localhost:8000/$relativeDir/src"

google-chrome-stable --auto-open-devtools-for-tabs $url &
urxvtc -title s3t1 -hold -e tmux new-session\; send-keys 'vim' Enter &
urxvtc -hold -e livereload . -x hx &
urxvtc -title s2t2 &
urxvtc -title s2t2 &
